### ISSUE TITLE
[Security risk] Docker login action write login auth token to disk

### ISSUE THREAD

**Issue by TingluoHuang** [Azure/container-actions#3]
https://github.com/Azure/container-actions/blob/master/docker-login/src/login.ts#L16

Why do we need to create a docker config file and write the base64 encoded password to disk? From what i understand, docker has it's own credential store which will handle credential secure for you when you run `docker login`, like `osxkeychain`, `windows cred manager`, etc.

**Comment by thesattiraju** [comment]
The only major reason for using this approach is to ensure clean up from the machine, given that it's being created in the temp_directory of the runner.

If we used `osxkeychain` or a `windows cred manager` (FYI, docker Linux would be doing whatever we're doing in our current approach, i.e. the insecure writing to file), adding `docker-logout` step would be mandatory to every workflow. And if that's missed, there's was a potential security risk of the values staying on the machine even after the workflow is completed. 

Eventually, when the private runner's scenario would light up, these credentials would end up staying on that machine if `docker-logout` step wasn't used leading to much higher risks cause of shared resources.

We could throw in an explicit warning to warn the users about our current approach in the logs.
